version: 2
jobs:
  deploy:
    machine:
      enabled: true
    environment:
      SERVER: "176.9.105.119"
    steps:
      - run: ssh-keyscan $SERVER >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "9f:2a:2a:00:43:76:68:7b:9f:63:61:54:e8:53:04:63"
      - run:
          name: Deploy to prod
          command: |
            ssh root@176.9.105.119 '/bin/bash -l -c "
            source /root/.bashrc
            source /root/.nvm/nvm.sh
            cd /root/simulatorradio/nuxt
            git checkout .
            git checkout master
            git pull
            npm install
            npm run build
            pm2 restart sr-nuxt"'

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-build
      - deploy:
          requires:
            - test-build
          filters:
            branches:
              only:
                - master
      - purge-cache:
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
      - notify-dev-lounge:
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
