version: 2
jobs:
  build:
    machine:
      enabled: true
    environment:
      SERVER: "176.9.105.119"
    steps:
      - run: ssh-keyscan $SERVER >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "9f:2a:2a:00:43:76:68:7b:9f:63:61:54:e8:53:04:63"
      - checkout
      - run:
        name: Install node
        command: |
          set +e
          curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
          export NVM_DIR="/opt/circleci/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm install v10.16.2
          nvm alias default v10.16.2

          # Each step uses the same `$BASH_ENV`, so need to modify it
          echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
          echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build prod
          command: npm run build:prod

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
