version: 2
jobs:
  build:
    machine:
      enabled: true
    environment:
      SERVER: "176.9.105.119"
    steps:
      - run: ssh-keyscan $SERVER >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "9f:2a:2a:00:43:76:68:7b:9f:63:61:54:e8:53:04:63"
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build prod
          command: npm run build:prod

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
