version: 2
jobs:
  deploy:
    environment:
      SERVER: "176.9.105.119"
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build prod
          command: npm run build:prod
      - store_artifacts:
          path: dist/rigs-of-rods



workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
