version: 2
jobs:
  deploy:
    environment:
      SERVER: "176.9.105.119"
    steps:
      - run: ssh-keyscan $SERVER >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "9f:2a:2a:00:43:76:68:7b:9f:63:61:54:e8:53:04:63"
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: angular-build
          command: npm run build:prod


workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-build
      - deploy:
          requires:
            - test-build
          filters:
            branches:
              only:
                - master
      - purge-cache:
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
      - notify-dev-lounge:
          requires:
            - deploy
          filters:
            branches:
              only:
                - master
